### ISSUE TITLE
Yotta requiring GitHub signin

### ISSUE THREAD

**Issue by Bottersnike** [jamesadevine/microbit#3]
When trying to automate the build process, yotta always crashes because I'm running in non interactive (-n) mode and as such is unable to open my browser to login. Why is a login needed? Doesn't it scare away people? Is there a way to bypass logging in?

**Comment by jamesadevine** [comment]
Hi @Bottersnike, we currently have an issue open in microbit-samples (https://github.com/lancaster-university/microbit-samples/issues/6)

There is a workaround pending a formal solution from ARM 😄 

Closing.
