### ISSUE TITLE
nrf_sco.h not found

### ISSUE THREAD

**Issue by Lithimlin** [jamesadevine/microbit#8]
I've been trying to piece together this "library" together with the mbed-os library and the dal library and have now run into an error:
"MicroBit/MicroBit.cpp:41:21: fatal error: nrf_soc.h: No such file or directory"
I've been correcting paths for the last hour but I cannot find this file anywhere in neither the mbed-os nor the dal libraries. Is this a typo or where can I get this file from?

**Comment by jamesadevine** [comment]
@Lithimlin microbit-dal runs on mbed classic 2.0, not mbed OS.

https://github.com/lancaster-university/nrf51-sdk/blob/master/source/nordic_sdk/components/softdevice/s130/headers/nrf_soc.h
is where that file is located.

**Comment by Lithimlin** [comment]
Ah, thank you.

**Comment by jamesadevine** [comment]
P.S. if your goal is to run mbed-os on microbit, I'd advise that you look at the RAM usage beforehand, especially if you also want to use BLE. Last time we checked, RAM usage was higher than mbed-classic, which leaves very little space for user apps.

**Comment by Lithimlin** [comment]
My plan as of now is only to be able to use the MicroBit library. Since the README did not specify what else would be needed besides the microbit-dal, I did a google search for one of the missing files and ended up in the mbed-os library.
If you would be so kind to explain how to set up this library correctly, I'd be more than happy to just do that.

**Comment by jamesadevine** [comment]
https://lancaster-university.github.io/microbit-docs/offline-toolchains/

If you install yotta, all the dependencies will be managed for you.

```
┗━ microbit 2.0.0-rc9
  ┗━ microbit-dal 2.0.0-rc9 yotta_modules/microbit-dal
    ┣━ mbed-classic 0.0.4 yotta_modules/mbed-classic
    ┣━ ble 2.5.0 yotta_modules/ble
    ┣━ ble-nrf51822 2.5.0 yotta_modules/ble-nrf51822
    ┗━ nrf51-sdk 2.2.0 yotta_modules/nrf51-sdk
```

These modules are all available from https://github.com/lancaster-university

**Comment by Lithimlin** [comment]
I don't have to be using mbed together with yotta though, right? It just helps me install all the modules needed and I could use any IDE of my choice?

**Comment by jamesadevine** [comment]
@Lithimlin yotta is simply a wrapper around your command line compiler that handles software dependencies, and the compilation of those dependencies. It is offline, so yes, you can use your own editor for writing code.

**Comment by Lithimlin** [comment]
Alright. Thank you very much.
